use_frameworks!

platform :ios, '8.0'

target 'LNModulizeTestKit_Example' do
  pod 'LNModulizeTestKit', :path => '../'

  target 'LNModulizeTestKit_Tests' do
    inherit! :search_paths

    
  end
end
